# Generated by Django 6.0.4 on 2026-05-09 18:45

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import education.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Электронная почта')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('administrator', 'Администратор')], default='student', max_length=20, verbose_name='Роль')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['last_name', 'first_name', 'username'],
            },
            managers=[
                ('objects', education.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('curator', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curated_groups', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='academic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='education.academicgroup', verbose_name='Учебная группа'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('auth', 'Авторизация'), ('profile', 'Профиль'), ('test', 'Тест'), ('analytics', 'Аналитика'), ('admin', 'Администрирование')], max_length=20, verbose_name='Тип действия')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал действия',
                'verbose_name_plural': 'Журнал действий',
                'db_table': 'logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Дисциплина')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('groups', models.ManyToManyField(blank=True, related_name='disciplines', to='education.academicgroup', verbose_name='Учебные группы')),
                ('teachers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='disciplines_taught', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'disciplines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='education.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'db_table': 'answer_options',
                'ordering': ['order', 'id'],
                'unique_together': {('question', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, verbose_name='Лимит времени (мин.)')),
                ('max_attempts', models.PositiveIntegerField(default=1, verbose_name='Максимум попыток')),
                ('allow_retake', models.BooleanField(default=False, verbose_name='Разрешить повторное прохождение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('available_from', models.DateTimeField(blank=True, null=True, verbose_name='Доступен с')),
                ('available_to', models.DateTimeField(blank=True, null=True, verbose_name='Доступен до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='education.discipline', verbose_name='Дисциплина')),
                ('groups', models.ManyToManyField(blank=True, related_name='tests', to='education.academicgroup', verbose_name='Доступные группы')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'tests',
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1, verbose_name='Номер попытки')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Набрано баллов')),
                ('max_score', models.PositiveIntegerField(default=0, verbose_name='Максимум баллов')),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Оценка')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершён')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='education.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождения',
                'db_table': 'test_attempts',
                'ordering': ['-started_at'],
                'unique_together': {('student', 'test', 'attempt_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'order')},
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.question', verbose_name='Вопрос')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_answers', to='education.answeroption', verbose_name='Выбранный вариант')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.testattempt', verbose_name='Попытка')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'db_table': 'student_answers',
                'ordering': ['question__order', 'id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
