# Generated by Django 6.0.4 on 2026-04-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentanswer',
            options={'ordering': ['question__order', 'id'], 'verbose_name': 'Ответ студента', 'verbose_name_plural': 'Ответы студентов'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
