# Generated by Django 6.0.4 on 2026-05-04 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
