# Generated by Django 6.0.4 on 2026-05-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicgroup',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='activitylog',
            table='logs',
        ),
        migrations.AlterModelTable(
            name='answeroption',
            table='answer_options',
        ),
        migrations.AlterModelTable(
            name='discipline',
            table='disciplines',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='studentanswer',
            table='student_answers',
        ),
        migrations.AlterModelTable(
            name='test',
            table='tests',
        ),
        migrations.AlterModelTable(
            name='testattempt',
            table='test_attempts',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
