# центральный модуль собирает view-функции из тематических файлов для urls.py
from .admin_views import (
    activity_logs,
    activity_logs_clear,
    admin_dashboard,
    admin_user_create,
    admin_user_delete,
    admin_user_edit,
    admin_user_list,
    admin_user_reset_password,
    admin_user_toggle_active,
    discipline_create,
    discipline_delete,
    discipline_edit,
    discipline_list,
    group_create,
    group_delete,
    group_edit,
    group_list,
)
from .public_views import (
    dashboard,
    home,
    password_reset_info,
    personal_data_consent,
    privacy_policy,
    profile_edit,
    register,
)
from .student_views import (
    attempt_result,
    finish_attempt,
    save_answer,
    start_test,
    student_dashboard,
    take_test,
)
from .teacher_views import (
    question_create,
    question_delete,
    question_image_delete,
    question_update,
    report_detail,
    teacher_dashboard,
    test_create,
    test_delete,
    test_preview,
    test_results_export,
    test_update,
)
